Repository utilForever/CubbyTower, pull requests merged in 2022-03, with the labels that each got.

#40 Implement key input system
  Includes/CubbyTower/Components/Inputs.hpp
  Includes/CubbyTower/Helpers/InputHelpers.hpp
  Includes/CubbyTower/Systems/UpgradeSystem.hpp
  Sources/CubbyTower/Game.cpp
  Sources/CubbyTower/Helpers/InputHelpers.cpp
  Sources/CubbyTower/Helpers/TowerHelpers.cpp
  Sources/CubbyTower/Systems/InputSystem.cpp
  Sources/CubbyTower/Systems/UpgradeSystem.cpp
  Sources/CubbyTower/main.cpp
  Tests/UnitTests/Systems/UpgradeSystemTests.cpp
Labels: size/L

#41 Implement monster destroy system
  Includes/CubbyTower/Components/Destroyable.hpp
  Includes/CubbyTower/Helpers/MonsterHelpers.hpp
  Sources/CubbyTower/Helpers/MonsterHelpers.cpp
  Sources/CubbyTower/Systems/AttackSystem.cpp
  Tests/UnitTests/Helpers/MonsterHelpersTests.cpp
  Tests/UnitTests/Systems/AttackSystemTests.cpp
Labels: size/M

#42 Implement tooltip system
  Includes/CubbyTower/Commons/Tags.hpp
  Includes/CubbyTower/Systems/TooltipSystem.hpp
  Sources/CubbyTower/Game.cpp
  Sources/CubbyTower/Systems/TooltipSystem.cpp
Labels: size/M

#45 Fix CI system errors
  .github/workflows/codeql-analysis.yml
  .github/workflows/windows.yml
Labels: size/S

#43 Fix minor typo
  Includes/CubbyTower/Helpers/MonsterHelpers.hpp
Labels: size/XS

#46 Implement targeting system
  Includes/CubbyTower/Commons/Enums.hpp
  Includes/CubbyTower/Components/FindTarget.hpp
  Includes/CubbyTower/Components/Target.hpp
  Includes/CubbyTower/Components/TargetPriority.hpp
  Includes/CubbyTower/Components/Targeter.hpp
  Includes/CubbyTower/Helpers/TowerHelpers.hpp
  Sources/CubbyTower/Helpers/MonsterHelpers.cpp
  Sources/CubbyTower/Helpers/ProjectileHelpers.cpp
  Sources/CubbyTower/Helpers/TowerHelpers.cpp
  Sources/CubbyTower/Systems/AttackSystem.cpp
  Tests/UnitTests/Helpers/MonsterHelpersTests.cpp
  Tests/UnitTests/Systems/AttackSystemTests.cpp
Labels: size/L
